# Generated by Django 2.1 on 2018-12-15 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
